version: '3.7'

services:
  postgres:
    image: postgres:13.0
    secrets:
      - keycloak_db_user
      - keycloak_db_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/keycloak_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/keycloak_db_password
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data

secrets:
  keycloak_db_user:
    external: true
  keycloak_db_password:
    external: true

volumes:
  postgres-data:
