FROM jboss/keycloak:15.0.2

COPY providers/prox-keycloak-spi/target/prox-keycloak-spi.jar /opt/jboss/keycloak/standalone/deployments/

COPY themes/target/prox-keycloak-themes.jar /opt/jboss/keycloak/standalone/deployments/
