FROM jboss/keycloak:16.0.0

COPY providers/prox-keycloak-spi/target/prox-keycloak-spi.jar /opt/jboss/keycloak/standalone/deployments/

COPY themes/target/prox-keycloak-themes.jar /opt/jboss/keycloak/standalone/deployments/
