FROM jboss/keycloak:15.0.2

COPY prox-keycloak-spi/target/prox-keycloak-spi.jar /opt/jboss/keycloak/standalone/deployments/prox-keycloak-spi.jar

COPY prox-keycloak-theme/target/prox-keycloak-theme.jar /opt/jboss/keycloak/standalone/deployments/prox-keycloak-theme.jar

COPY configuration/standalone-ha-no-cache.xml /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
